spring:
  application:
    name: htmx-learning # アプリケーションの名前を指定しています。
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    locations: classpath:db/migration
    user: postgres
    password: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    hikari:
      maximum-pool-size: 20
      connection-timeout: 60000
      minimum-idle: 5
      max-lifetime: 30000
  threads:
    virtual:
      enabled: true # 仮想スレッドの使用を有効にしています。
  jpa:
    open-in-view: true
    show-sql: true

server:
  port: 8080 # サーバーがリッスンするポート番号を指定します。
  shutdown: graceful   # サーバーのシャットダウン方法を指定します。ここではgraceful（優雅なシャットダウン）となっています。
  graceful:
    shutdown:
      # 30秒経過後もまだ未完了のリクエストがある場合、Spring Bootはこれらのリクエストを強制的に中断し、アプリケーションをシャットダウンします。
      timeout: 30s # シャットダウンを待機する最大時間を30秒に設定

logging:
  group:
    root: WARN
